openapi: 3.0.0
info:
  title: Create Calendar Event
  version: 1.0.0
paths:
  /:
    post:
      summary: Create a calendar event
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                event_title:
                  type: string
                start_time:
                  type: string
                end_time:
                  type: string
                location:
                  type: string
                doctor_name:
                  type: string
                phone_number:
                  type: string
                notes:
                  type: string
              required:
                - event_title
                - start_time
                - end_time
      responses:
        '200':
          description: Event created
