openapi: 3.1.0
info:
  title: Create Calendar Event
  version: 1.0.0
servers:
  - url: https://hooks.zapier.com/hooks/catch/22681925/2p6jt8o/
paths:
  /:
    post:
      summary: Create a calendar event
      operationId: createCalendarEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_title:
                  type: string
                  description: Title of the event (e.g., Doctor Appointment with Dr. Smith)
                start_time:
                  type: string
                  description: ISO 8601 Start Time (e.g., 2025-04-30T13:00:00)
                end_time:
                  type: string
                  description: ISO 8601 End Time (e.g., 2025-04-30T14:00:00)
                location:
                  type: string
                  description: Location of the event (e.g., 123 Oak Street, Springfield)
                doctor_name:
                  type: string
                  description: Name of the doctor (e.g., Dr. Smith)
                phone_number:
                  type: string
                  description: Phone number associated with the appointment
                notes:
                  type: string
                  description: Additional notes (e.g., "Bring insurance card")
              required:
                - event_title
                - start_time
                - end_time
